server:
  port: 9002
dubbo:
  application:
    name: weifuwu-search-service
  registry:
    protocol: zookeeper
    address: weifuwu.xiakai.online:2181
  consumer:
    timeout: 3000
spring:
  thymeleaf:
    suffix: .html
    cache: false