dubbo:
  application:
    name: weifuwu-index-service
  registry:
    protocol: zookeeper
    address: weifuwu.xiakai.online:2181
  consumer:
    timeout: 3000
server:
  port: 80
spring:
  thymeleaf:
    suffix: .html
    cache: false
  rabbitmq:
    host: 0000
    username: 123
    password: asdf
    virtual-host: /ajsdfh
    port: 4242
