dubbo:
  application:
    name: weifuwu-background-service
  registry:
    protocol: zookeeper
    address: weifuwu.xiakai.online:2181
  consumer:
    timeout: 3000
server:
  port: 9001
spring:
  thymeleaf:
    suffix: .html
    cache: false
