dubbo:
  application:
    name: weifuwu-background-service
  registry:
    protocol: zookeeper
    address: 39.106.85.109:2181
  consumer:
    timeout: 3000
server:
  port: 9090
spring:
  thymeleaf:
    suffix: .html
    cache: false
